
-- CREACION DE TABLAS

CREATE TABLE PLACE (
    ID               VARCHAR2(255),
    UPDATED_AT       DATE,
    CREATED_AT       DATE,
    USER_ID          VARCHAR2(255),
    NAME             VARCHAR2(255),
    CITY_ID          VARCHAR2(255),
    DESCRIPTION      VARCHAR2(255),
    NUMBER_ROOMS     NUMBER,
    NUMBER_BATHROOMS NUMBER,
    MAX_GUEST        NUMBER,
    PRICE_BY_NIGHT   NUMBER,
    LATITUDE         NUMBER,
    LONGITUDE        NUMBER
);

CREATE TABLE AMENITY (
    ID           VARCHAR2(255),
    UPDATED_AT   DATE,
    CREATED_AT   DATE,
    NAME         VARCHAR2(255)
);

CREATE TABLE PLACEAMENITY (
    AMENITY_ID VARCHAR2(255),
    PLACE_ID   VARCHAR2(255)
);

CREATE TABLE STATE (
    ID           VARCHAR2(255),
    UPDATED_AT   DATE,
    CREATED_AT   DATE,
    NAME         VARCHAR2(255)
);

CREATE TABLE CITY (
    ID           VARCHAR2(255),
    UPDATED_AT   DATE,
    CREATED_AT   DATE,
    STATE_ID     VARCHAR2(255),
    NAME         VARCHAR2(255)
);

CREATE TABLE REVIEW (
    ID           VARCHAR2(255),
    UPDATED_AT   DATE,
    CREATED_AT   DATE,
    USER_ID      VARCHAR2(255),
    PLACE_ID     VARCHAR2(255),
    TEXT         VARCHAR2(255)
);

CREATE TABLE USERS (
    ID           VARCHAR2(255),
    UPDATED_AT   DATE,
    CREATED_AT   DATE,
    EMAIL        VARCHAR2(255),
    PASSWORD     VARCHAR2(255),
    FIRST_NAME   VARCHAR2(255),
    LAST_NAME    VARCHAR2(255)
);



-- CONSTRAINTS

-- claves primarias 

ALTER TABLE PLACE
ADD CONSTRAINT PK_PLACE PRIMARY KEY (ID);

ALTER TABLE AMENITY
ADD CONSTRAINT PK_AMENITY PRIMARY KEY (ID);

ALTER TABLE STATE
ADD CONSTRAINT PK_STATE PRIMARY KEY (ID);

ALTER TABLE CITY
ADD CONSTRAINT PK_CITY PRIMARY KEY (ID);

ALTER TABLE REVIEW
ADD CONSTRAINT PK_REVIEW PRIMARY KEY (ID);

ALTER TABLE USERS
ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);


-- claves foráneas

-- FK PLACE

ALTER TABLE PLACE
ADD CONSTRAINT FK_PLACE_USERS FOREIGN KEY (USER_ID)
REFERENCES USERS(ID);

ALTER TABLE PLACE
ADD CONSTRAINT FK_PLACE_CITY FOREIGN KEY (CITY_ID)
REFERENCES CITY(ID);

-- FK PLACEAMENITY

ALTER TABLE PLACEAMENITY
ADD CONSTRAINT FK_PLACEAMENITY_AMENITY FOREIGN KEY (AMENITY_ID)
REFERENCES AMENITY(ID);

ALTER TABLE PLACEAMENITY
ADD CONSTRAINT FK_PLACEAMENITY_PLACE FOREIGN KEY (PLACE_ID)
REFERENCES PLACE(ID);

-- FK CITY

ALTER TABLE CITY
ADD CONSTRAINT FK_CITY_STATE FOREIGN KEY (STATE_ID)
REFERENCES STATE(ID);

-- FK REVIEW

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_USERS FOREIGN KEY (USER_ID)
REFERENCES USERS(ID);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_PLACE FOREIGN KEY (PLACE_ID)
REFERENCES PLACE(ID);

-- constrains default tabla PLACE

ALTER TABLE PLACE
MODIFY (NUMBER_ROOMS     NUMBER DEFAULT 0);

ALTER TABLE PLACE
MODIFY (NUMBER_BATHROOMS NUMBER DEFAULT 0);

ALTER TABLE PLACE
MODIFY (MAX_GUEST        NUMBER DEFAULT 0);

ALTER TABLE PLACE
MODIFY (PRICE_BY_NIGHT   NUMBER DEFAULT 0);
